
package Thumper is
   -- reference: https://github.com/pchapin/thumper/blob/master/doc/Theory.xml
   
   -- The time stamp protocol begins when Alice wants to be able to prove later that one of
   -- her documents existed at (or before) the current time. She first computes a cryptographic
   -- hash of the document using a suitable secure hash algorithm. She then presents this hash
   -- to a trusted third party time stamping server. The server appends the current time to the
   -- end of the hash, signs the resulting data to make the official time stamp, and returns the
   -- time stamp to Alice. Alice keeps the time stamp with the document.</para>

   -- To verify the time stamp a person need only verify the signature of the time stamp
   -- server and then verify that the document has the same hash as that stored in the time
   -- stamp.   
   
   -- Vulnerabilities
   -- (1) the attacker cannot change the time on the server
   -- (2) make sure the safety of the public/private key
   
   -- make sure the absence of “information leak” for private key that: the server never transmits
   -- any information pertaining to the private key except for the signatures generated by it.   
   
   
   -- server side data --
   TopKey: Integer;
   Key: Integer;
   Time: Integer;
   
   -- client side data --
   Document: Integer;
   DocSignature: Integer;
   
   -- functions --
   procedure Tick(Time: in out Integer);
   
   procedure AppendTime(U: in Integer; V: out Integer);
   
   procedure Sign(Data: in Integer; Signature: out Integer);
   
   procedure MakeSignature(Data: in Integer; 
			   Signature: out Integer);  
   
   procedure Hash(X: in Integer; Y: out Integer);
   
   -- main --
   procedure MainProc;
   
end Thumper;
